### PR TITLE
MEEP-132 Install auth on Mapped NextJS app

### PR DESCRIPTION
**Pull request by joaquimds**
## Description
This PR 
- adds a fresh installation of NextJs v13 into the repo 
- adds launch settings to run frontend and backend with play button in run and debug
- sets up a basic authentication system with JWT

## Motivation and Context
Addresses issue [MEEP-132](https://linear.app/commonknowledge/issue/MEEP-132/install-auth-on-mapped-nextjs-app)

## How Can It Be Tested?
Download the branch and run by pressing play on App in the VSCode Run and Debug panel
Open up a shell inside the Django web container by running:
```
cd django
docker compose exec web bash
```
then run 
`python manage.py createsuperuser `
to create an account

You should be able to login then at http://localhost:8000/accounts/login/

Go to the Django admin and make sure your user status is verified
http://localhost:8000/admin/gqlauth/userstatus/

Untitled

Create an .env.local file in the root of the project and add the graphql backend url
`NEXT_PUBLIC_BACKEND_BASE_URL="http://localhost:8000/graphql"`

Go to http://localhost:3000/login fill out the form to login. Use the same credentials as with Django

You should be redirected to http://localhost:3000/account

Click on the logout page on the menu and click the button to logout

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by conatus** [comment]
@Moggach 

Could you please fill in our standard pull request template for this PR? Most crucially here, it is unclear how I test any of this. I can work it out, but it would be great to know a bit more clearly.

Thank you.

**Comment by conatus** [comment]
@joaquimds @Moggach 

Thinking about the general approach here, this severs easy upstream compatibility with the mySociety Local Intelligence Hub, by virtue of moving all the files into a sub-directory. 

If the goal here is a mono-repo for front-end and backend code, this it necessary to make this change? It makes it all neater, sure. But the downside is that merges to and from upstream and much harder. We are going to end up fixing bugs from upstream which it would be nice to contribute back relatively quickly. In the more common situation, we are going to want to absorb any bug fixes and new datasets from upstream, as mySociety will see them faster than we do as it is running in production.

I think if it is really hard to not make this change, then we can proceed, as we are still in relative prototyping mode. Down the line we could work out how to do this in a better way, or work out some automation to make things smoother. 

But there is nothing more permanent than a temporary decision and if it isn't too hard to achieve the same goal by not moving everything to a breaking sub-directory, I think we should do it.

**Comment by Moggach** [comment]
> @joaquimds @Moggach
> 
> Thinking about the general approach here, this severs easy upstream compatibility with the mySociety Local Intelligence Hub, by virtue of moving all the files into a sub-directory.
> 
> If the goal here is a mono-repo for frontend and backend code, this it necessary to make this change? It makes it all neater, sure. But the downside is that merges to and from upstream and much harder. We are going to end up fixing bugs from upstream which it would be nice to contribute back relatively quickly. In the more common situation, we are going to want to absorb any bug fixes and new datasets from upstream, as mySociety will see them faster than we do as it is running in production.
> 
> I think if it is really hard to not make this change, then we can proceed, as we are still in relative prototyping mode. Down the line we could work out how to do this in a better way, or work out some automation to make things smoother.
> 
> But there is nothing more permanent than a temporary decision and if it isn't too hard to achieve the same goal by not moving everything to a breaking sub-directory, I think we should do it.

Do you mean keep Django in the main directory and just have a sub-directory for the Next frontend?

**Comment by conatus** [comment]
> Do you mean keep Django in the main directory and just have a sub-directory for the Next frontend?

Yes.

**Comment by Moggach** [comment]
> > Do you mean keep Django in the main directory and just have a sub-directory for the Next frontend?
> 
> Yes.

I'll check with @joaquimds when he's back but definitely see the rationale for this

**Pull request merged**
