### PR TITLE
Building marketing pages

### PR DESCRIPTION
**Pull request by Arbyhisenaj**
Built some of the marketing side of the website

## Description

For the marketing side of the website (when the user is not logged in) I built:

- a new nav using shadcn dropdown component which works really well
- that proposes having a similar site structure of Features, Integrations, support and about.
- I've built a template for the feature pages but will need to come back to it when the product is ready to insert the real content

## Motivation and Context

It allows us to have something for the marketing side of the page to test amongst ourselves and begin the process of developing content for.

## How Can It Be Tested?

I think we can take a look at it internally and judge if it's going in the right direction.

## How Will This Be Deployed?

I'm not sure about this one technically

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I've checked the spec (e.g. Figma file) and documented any divergences.
- [x] My code follows the code style of this project.
- My change requires a change to the documentation.
- I've updated the documentation accordingly.
- [x] Replace unused checkboxes with bullet points.

### CODE REVIEW

**Comment by conatus** [comment]
@Arbyhisenaj 

Could you fully fill out the pull request template please? Thanks!

**Comment by Arbyhisenaj** [comment]
done sorry

**Comment by conatus** [comment]
Thanks @Arbyhisenaj 

I am sort of expecting a branch deploy to magically spin up, what's the situation here @joaquimds?

**Comment by conatus** [comment]
Once #25 goes in, `main` can be merged into this branch and all the tests should pass. They are failing right now because the setup surrounding the tests has drifted from where the tests are at by the look of things.

**Comment by janbaykara** [comment]
I'm merging this in now.

**Pull request closed without merging**
